// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.DoctorIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DoctorIntegrationTest_Roo_Configurable {
    
    declare @type: DoctorIntegrationTest: @Configurable;
    
}
