// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.HospitalEmployeeDataOnDemand;
import com.xebia.wartelist.domain.HospitalEmployeeIntegrationTest;
import com.xebia.wartelist.service.HospitalEmployeeService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect HospitalEmployeeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HospitalEmployeeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HospitalEmployeeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    HospitalEmployeeDataOnDemand HospitalEmployeeIntegrationTest.dod;
    
    @Autowired
    HospitalEmployeeService HospitalEmployeeIntegrationTest.hospitalEmployeeService;
    
    @Test
    public void HospitalEmployeeIntegrationTest.testCountAllHospitalEmployees() {
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", dod.getRandomHospitalEmployee());
        long count = hospitalEmployeeService.countAllHospitalEmployees();
        Assert.assertTrue("Counter for 'HospitalEmployee' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HospitalEmployeeIntegrationTest.testFindHospitalEmployee() {
        HospitalEmployee obj = dod.getRandomHospitalEmployee();
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to provide an identifier", id);
        obj = hospitalEmployeeService.findHospitalEmployee(id);
        Assert.assertNotNull("Find method for 'HospitalEmployee' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HospitalEmployee' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HospitalEmployeeIntegrationTest.testFindAllHospitalEmployees() {
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", dod.getRandomHospitalEmployee());
        long count = hospitalEmployeeService.countAllHospitalEmployees();
        Assert.assertTrue("Too expensive to perform a find all test for 'HospitalEmployee', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HospitalEmployee> result = hospitalEmployeeService.findAllHospitalEmployees();
        Assert.assertNotNull("Find all method for 'HospitalEmployee' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HospitalEmployee' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HospitalEmployeeIntegrationTest.testFindHospitalEmployeeEntries() {
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", dod.getRandomHospitalEmployee());
        long count = hospitalEmployeeService.countAllHospitalEmployees();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HospitalEmployee> result = hospitalEmployeeService.findHospitalEmployeeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HospitalEmployee' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HospitalEmployee' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HospitalEmployeeIntegrationTest.testSaveHospitalEmployee() {
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", dod.getRandomHospitalEmployee());
        HospitalEmployee obj = dod.getNewTransientHospitalEmployee(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HospitalEmployee' identifier to be null", obj.getId());
        hospitalEmployeeService.saveHospitalEmployee(obj);
        Assert.assertNotNull("Expected 'HospitalEmployee' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HospitalEmployeeIntegrationTest.testDeleteHospitalEmployee() {
        HospitalEmployee obj = dod.getRandomHospitalEmployee();
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HospitalEmployee' failed to provide an identifier", id);
        obj = hospitalEmployeeService.findHospitalEmployee(id);
        hospitalEmployeeService.deleteHospitalEmployee(obj);
        Assert.assertNull("Failed to remove 'HospitalEmployee' with identifier '" + id + "'", hospitalEmployeeService.findHospitalEmployee(id));
    }
    
}
