// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.OperationType;
import com.xebia.wartelist.domain.OperationTypeDataOnDemand;
import com.xebia.wartelist.service.OperationTypeService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect OperationTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OperationTypeDataOnDemand: @Component;
    
    private Random OperationTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<OperationType> OperationTypeDataOnDemand.data;
    
    @Autowired
    OperationTypeService OperationTypeDataOnDemand.operationTypeService;
    
    public OperationType OperationTypeDataOnDemand.getNewTransientOperationType(int index) {
        OperationType obj = new OperationType();
        setName(obj, index);
        return obj;
    }
    
    public void OperationTypeDataOnDemand.setName(OperationType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public OperationType OperationTypeDataOnDemand.getSpecificOperationType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OperationType obj = data.get(index);
        BigInteger id = obj.getId();
        return operationTypeService.findOperationType(id);
    }
    
    public OperationType OperationTypeDataOnDemand.getRandomOperationType() {
        init();
        OperationType obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return operationTypeService.findOperationType(id);
    }
    
    public boolean OperationTypeDataOnDemand.modifyOperationType(OperationType obj) {
        return false;
    }
    
    public void OperationTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = operationTypeService.findOperationTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OperationType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OperationType>();
        for (int i = 0; i < 10; i++) {
            OperationType obj = getNewTransientOperationType(i);
            try {
                operationTypeService.saveOperationType(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
