// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.OperationTypeDataOnDemand;
import com.xebia.wartelist.domain.OperationTypeIntegrationTest;
import com.xebia.wartelist.service.OperationTypeService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect OperationTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OperationTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OperationTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    OperationTypeDataOnDemand OperationTypeIntegrationTest.dod;
    
    @Autowired
    OperationTypeService OperationTypeIntegrationTest.operationTypeService;
    
    @Test
    public void OperationTypeIntegrationTest.testCountAllOperationTypes() {
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", dod.getRandomOperationType());
        long count = operationTypeService.countAllOperationTypes();
        Assert.assertTrue("Counter for 'OperationType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OperationTypeIntegrationTest.testFindOperationType() {
        OperationType obj = dod.getRandomOperationType();
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OperationType' failed to provide an identifier", id);
        obj = operationTypeService.findOperationType(id);
        Assert.assertNotNull("Find method for 'OperationType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'OperationType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OperationTypeIntegrationTest.testFindAllOperationTypes() {
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", dod.getRandomOperationType());
        long count = operationTypeService.countAllOperationTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'OperationType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<OperationType> result = operationTypeService.findAllOperationTypes();
        Assert.assertNotNull("Find all method for 'OperationType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'OperationType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OperationTypeIntegrationTest.testFindOperationTypeEntries() {
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", dod.getRandomOperationType());
        long count = operationTypeService.countAllOperationTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<OperationType> result = operationTypeService.findOperationTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'OperationType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'OperationType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OperationTypeIntegrationTest.testSaveOperationType() {
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", dod.getRandomOperationType());
        OperationType obj = dod.getNewTransientOperationType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'OperationType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'OperationType' identifier to be null", obj.getId());
        operationTypeService.saveOperationType(obj);
        Assert.assertNotNull("Expected 'OperationType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OperationTypeIntegrationTest.testDeleteOperationType() {
        OperationType obj = dod.getRandomOperationType();
        Assert.assertNotNull("Data on demand for 'OperationType' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'OperationType' failed to provide an identifier", id);
        obj = operationTypeService.findOperationType(id);
        operationTypeService.deleteOperationType(obj);
        Assert.assertNull("Failed to remove 'OperationType' with identifier '" + id + "'", operationTypeService.findOperationType(id));
    }
    
}
