// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.OperationDataOnDemand;
import com.xebia.wartelist.domain.OperationIntegrationTest;
import com.xebia.wartelist.service.OperationService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect OperationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OperationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OperationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    OperationDataOnDemand OperationIntegrationTest.dod;
    
    @Autowired
    OperationService OperationIntegrationTest.operationService;
    
    @Test
    public void OperationIntegrationTest.testCountAllOperations() {
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", dod.getRandomOperation());
        long count = operationService.countAllOperations();
        Assert.assertTrue("Counter for 'Operation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OperationIntegrationTest.testFindOperation() {
        Operation obj = dod.getRandomOperation();
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operation' failed to provide an identifier", id);
        obj = operationService.findOperation(id);
        Assert.assertNotNull("Find method for 'Operation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Operation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OperationIntegrationTest.testFindAllOperations() {
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", dod.getRandomOperation());
        long count = operationService.countAllOperations();
        Assert.assertTrue("Too expensive to perform a find all test for 'Operation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Operation> result = operationService.findAllOperations();
        Assert.assertNotNull("Find all method for 'Operation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Operation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OperationIntegrationTest.testFindOperationEntries() {
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", dod.getRandomOperation());
        long count = operationService.countAllOperations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Operation> result = operationService.findOperationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Operation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Operation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OperationIntegrationTest.testSaveOperation() {
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", dod.getRandomOperation());
        Operation obj = dod.getNewTransientOperation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Operation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Operation' identifier to be null", obj.getId());
        operationService.saveOperation(obj);
        Assert.assertNotNull("Expected 'Operation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OperationIntegrationTest.testDeleteOperation() {
        Operation obj = dod.getRandomOperation();
        Assert.assertNotNull("Data on demand for 'Operation' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Operation' failed to provide an identifier", id);
        obj = operationService.findOperation(id);
        operationService.deleteOperation(obj);
        Assert.assertNull("Failed to remove 'Operation' with identifier '" + id + "'", operationService.findOperation(id));
    }
    
}
