// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.HospitalDataOnDemand;
import com.xebia.wartelist.domain.OperationDataOnDemand;
import com.xebia.wartelist.domain.OperationTypeDataOnDemand;
import com.xebia.wartelist.domain.TimeSlot;
import com.xebia.wartelist.domain.TimeSlotDataOnDemand;
import com.xebia.wartelist.service.TimeSlotService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TimeSlotDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TimeSlotDataOnDemand: @Component;
    
    private Random TimeSlotDataOnDemand.rnd = new SecureRandom();
    
    private List<TimeSlot> TimeSlotDataOnDemand.data;
    
    @Autowired
    HospitalDataOnDemand TimeSlotDataOnDemand.hospitalDataOnDemand;
    
    @Autowired
    OperationDataOnDemand TimeSlotDataOnDemand.operationDataOnDemand;
    
    @Autowired
    OperationTypeDataOnDemand TimeSlotDataOnDemand.operationTypeDataOnDemand;
    
    @Autowired
    TimeSlotService TimeSlotDataOnDemand.timeSlotService;
    
    public TimeSlot TimeSlotDataOnDemand.getNewTransientTimeSlot(int index) {
        TimeSlot obj = new TimeSlot();
        setEndD(obj, index);
        setStartD(obj, index);
        return obj;
    }
    
    public void TimeSlotDataOnDemand.setEndD(TimeSlot obj, int index) {
        Date endD = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndD(endD);
    }
    
    public void TimeSlotDataOnDemand.setStartD(TimeSlot obj, int index) {
        Date startD = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartD(startD);
    }
    
    public TimeSlot TimeSlotDataOnDemand.getSpecificTimeSlot(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TimeSlot obj = data.get(index);
        BigInteger id = obj.getId();
        return timeSlotService.findTimeSlot(id);
    }
    
    public TimeSlot TimeSlotDataOnDemand.getRandomTimeSlot() {
        init();
        TimeSlot obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return timeSlotService.findTimeSlot(id);
    }
    
    public boolean TimeSlotDataOnDemand.modifyTimeSlot(TimeSlot obj) {
        return false;
    }
    
    public void TimeSlotDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = timeSlotService.findTimeSlotEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TimeSlot' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TimeSlot>();
        for (int i = 0; i < 10; i++) {
            TimeSlot obj = getNewTransientTimeSlot(i);
            try {
                timeSlotService.saveTimeSlot(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
