// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.xebia.wartelist.domain;

import com.xebia.wartelist.domain.TimeSlotDataOnDemand;
import com.xebia.wartelist.domain.TimeSlotIntegrationTest;
import com.xebia.wartelist.service.TimeSlotService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect TimeSlotIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TimeSlotIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TimeSlotIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    TimeSlotDataOnDemand TimeSlotIntegrationTest.dod;
    
    @Autowired
    TimeSlotService TimeSlotIntegrationTest.timeSlotService;
    
    @Test
    public void TimeSlotIntegrationTest.testCountAllTimeSlots() {
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", dod.getRandomTimeSlot());
        long count = timeSlotService.countAllTimeSlots();
        Assert.assertTrue("Counter for 'TimeSlot' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TimeSlotIntegrationTest.testFindTimeSlot() {
        TimeSlot obj = dod.getRandomTimeSlot();
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to provide an identifier", id);
        obj = timeSlotService.findTimeSlot(id);
        Assert.assertNotNull("Find method for 'TimeSlot' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TimeSlot' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TimeSlotIntegrationTest.testFindAllTimeSlots() {
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", dod.getRandomTimeSlot());
        long count = timeSlotService.countAllTimeSlots();
        Assert.assertTrue("Too expensive to perform a find all test for 'TimeSlot', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TimeSlot> result = timeSlotService.findAllTimeSlots();
        Assert.assertNotNull("Find all method for 'TimeSlot' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TimeSlot' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TimeSlotIntegrationTest.testFindTimeSlotEntries() {
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", dod.getRandomTimeSlot());
        long count = timeSlotService.countAllTimeSlots();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TimeSlot> result = timeSlotService.findTimeSlotEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TimeSlot' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TimeSlot' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TimeSlotIntegrationTest.testSaveTimeSlot() {
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", dod.getRandomTimeSlot());
        TimeSlot obj = dod.getNewTransientTimeSlot(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TimeSlot' identifier to be null", obj.getId());
        timeSlotService.saveTimeSlot(obj);
        Assert.assertNotNull("Expected 'TimeSlot' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TimeSlotIntegrationTest.testDeleteTimeSlot() {
        TimeSlot obj = dod.getRandomTimeSlot();
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TimeSlot' failed to provide an identifier", id);
        obj = timeSlotService.findTimeSlot(id);
        timeSlotService.deleteTimeSlot(obj);
        Assert.assertNull("Failed to remove 'TimeSlot' with identifier '" + id + "'", timeSlotService.findTimeSlot(id));
    }
    
}
